---
development:
  cloud_name: imgtitan
  api_key: '843797476168683'
  api_secret: K4-dk7Nnr-LNcRUwE72EfCgbw2Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: imgtitan
  api_key: '843797476168683'
  api_secret: K4-dk7Nnr-LNcRUwE72EfCgbw2Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: imgtitan
  api_key: '843797476168683'
  api_secret: K4-dk7Nnr-LNcRUwE72EfCgbw2Y
  enhance_image_tag: true
  static_image_support: false
